#pragma once

#define TARGETFPS				120
#define SCREEN_WIDTH			1600
#define SCREEN_HEIGHT			900

#ifdef NDEBUG
#define BOIDS_SPAWN				2000
#else
#define BOIDS_SPAWN				750
#endif 

#define BOIDS_SIZE				10
#define BOIDS_MINSPEED			200.0f
#define BOIDS_MAXSPEED			750.0f

#define BOIDS_CENTERINGFACTOR	0.025f
#define BOIDS_MATCHINGFACTOR	0.05f
#define BOIDS_AVOIDFACTOR		0.55f
#define BOIDS_AVOIDFACTOR_OBS	0.85f
#define BOIDS_OUTBOUNDS_TURNFAC 40.0f
#define BOIDS_NEAR_EDGE			25.0f

#define BOIDS_VISUALRANGE		50.0f
#define BOIDS_VISUALRANGE_SQR	BOIDS_VISUALRANGE * BOIDS_VISUALRANGE

#define BOIDS_PROTECTEDRANGE	15.0f
#define BOIDS_PROTECTEDRANGE_SQR	BOIDS_PROTECTEDRANGE * BOIDS_PROTECTEDRANGE

#define BOIDS_AVOID_TOPBOTTOM	true
#define BOIDS_AVOID_LEFTRIGHT	true
#define BOIDS_ALWAYSINBOUNDS	!(BOIDS_AVOID_TOPBOTTOM & BOIDS_AVOID_LEFTRIGHT)

#define BOIDS_MINSPEEDCOLOR { 129, 186, 219, 255 }
#define BOIDS_MAXSPEEDCOLOR { 255, 36, 36, 255 }

#define OBSTACLE_STARTCOUNT		15
#define OBSTACLE_MINIMUMRADIUS	45
#define OBSTACLE_MAXIMUMRADIUS	75

#define OBSATCLE_BORDER_MINMULT 0.15f
#define OBSATCLE_BORDER_MAXMULT 0.85f

#define OBSTACLE_PLAYERRADIUS	50