#pragma once

#define TARGETFPS				240

#define TRANSPARENTWINDOW		true

#define FULLSCREEN true

#define SCREEN_WIDTH			1920
#define SCREEN_HEIGHT			1080

#ifdef NDEBUG
#define BOIDS_SPAWN				6250
#else
#define BOIDS_SPAWN				1000
#endif 

#define BOIDS_SIZE				10
#define BOIDS_MINSPEED			150.0f
#define BOIDS_MAXSPEED			400.0f

#define BOIDS_CENTERINGFACTOR	0.0025f
#define BOIDS_MATCHINGFACTOR	0.05f
#define BOIDS_AVOIDFACTOR		5.5f
#define BOIDS_AVOIDFACTOR_OBS	10.5f
#define BOIDS_OUTBOUNDS_TURNFAC 20.0f
#define BOIDS_NEAR_EDGE			25.0f

#define BOIDS_VISUALRANGE		50.0f
#define BOIDS_VISUALRANGE_SQR	BOIDS_VISUALRANGE * BOIDS_VISUALRANGE

#define BOIDS_PROTECTEDRANGE	15.0f
#define BOIDS_PROTECTEDRANGE_SQR	BOIDS_PROTECTEDRANGE * BOIDS_PROTECTEDRANGE

#define BOIDS_AVOID_TOPBOTTOM	true
#define BOIDS_AVOID_LEFTRIGHT	true
#define BOIDS_ALWAYSINBOUNDS	!(BOIDS_AVOID_TOPBOTTOM & BOIDS_AVOID_LEFTRIGHT)

#define BOIDS_MINSPEEDCOLOR { 129, 186, 219, 255 }
#define BOIDS_MAXSPEEDCOLOR { 255, 36, 36, 255 }

#define OBSTACLE_STARTCOUNT		0
#define OBSTACLE_RANDSPAWN		10
#define OBSTACLE_MINIMUMRADIUS	45
#define OBSTACLE_MAXIMUMRADIUS	75

#define OBSATCLE_BORDER_MINMULT 0.15f
#define OBSATCLE_BORDER_MAXMULT 0.85f

#define OBSTACLE_PLAYERRADIUS	50

#define MOUSE_OBSTACLE_RADIUS 50

#define READ_VID false
#define VIDEOPATH "Foxes.mp4"